"""
ThreatSight Streamlit Dashboard v3.
Reads from scan_report.json generated by scan.py instead of
re-running the pipeline — avoids connection issues and is instant.
Can also trigger a fresh scan via scan.py subprocess.
"""

import streamlit as st
import json
import os
import sys
import subprocess
import time
from datetime import datetime

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

st.set_page_config(
    page_title="ThreatSight",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #1a2744 0%, #2563eb 100%);
        padding: 1.5rem 2rem;
        border-radius: 8px;
        margin-bottom: 1.5rem;
        color: white;
    }
    .stExpander { border: 1px solid #e5e7eb !important; border-radius: 6px !important; }
    div[data-testid="stMetricValue"] { font-size: 2rem !important; }
</style>
""", unsafe_allow_html=True)


def severity_emoji(severity):
    return {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")


def score_color(score):
    if score >= 70: return "#dc2626"
    if score >= 40: return "#d97706"
    return "#059669"


def load_scan_report(report_path: str) -> dict | None:
    if not os.path.exists(report_path):
        return None
    with open(report_path, "r") as f:
        return json.load(f)


def run_fresh_scan(profile_path: str, top_n: int, output_dir: str) -> bool:
    """Run scan.py as subprocess and wait for it to complete."""
    cmd = [sys.executable, "scan.py",
           "--profile", profile_path,
           "--top", str(top_n),
           "--output", output_dir]
    status = st.empty()
    status.info("Running scan pipeline... this takes 2-3 minutes. Watch the terminal for progress.")
    result = subprocess.run(cmd, capture_output=False)
    status.empty()
    return result.returncode == 0


# ── Sidebar ───────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### 🛡️ ThreatSight")
    st.markdown("---")
    st.markdown("**Configuration**")
    profile_path = st.text_input("Company Profile", value="company_profile.json")
    top_n        = st.slider("CVEs to Analyse", min_value=1, max_value=10, value=3)
    output_dir   = "reports"
    report_path  = os.path.join(output_dir, "scan_report.json")

    st.markdown("---")
    load_button  = st.button("📂 Load Last Scan", use_container_width=True,
                              help="Load results from reports/scan_report.json")
    scan_button  = st.button("🔍 Run Fresh Scan", type="primary", use_container_width=True,
                              help="Run scan.py to generate new results, then load them")
    if st.button("🗑️ Clear Results", use_container_width=True):
        st.session_state.pop("scan_result", None)
        st.session_state.pop("scan_done", None)
        st.rerun()

    st.markdown("---")
    st.caption("ThreatSight matches your asset inventory against real CVE data "
               "and generates AI-verified threat assessments for your specific stack.")

# ── Header ────────────────────────────────────────────────────
st.markdown("""
<div class="main-header">
    <h2 style="margin:0;font-size:1.6rem;">🛡️ ThreatSight</h2>
    <p style="margin:0;opacity:0.85;font-size:0.95rem;">
        Asset-Aware Vulnerability Intelligence — powered by NVD + CISA KEV + LangGraph
    </p>
</div>
""", unsafe_allow_html=True)

# ── Actions ───────────────────────────────────────────────────
if load_button:
    report = load_scan_report(report_path)
    if report:
        st.session_state["scan_result"] = report
        st.session_state["scan_done"]   = True
        st.success(f"Loaded scan report from {report_path}")
        st.rerun()
    else:
        st.error(f"No scan report found at {report_path}. Run a fresh scan first.")

if scan_button:
    if not os.path.exists(profile_path):
        st.error(f"Profile not found: {profile_path}")
    else:
        with st.spinner("Running scan pipeline (watch terminal for agent progress)..."):
            success = run_fresh_scan(profile_path, top_n, output_dir)
        if success:
            report = load_scan_report(report_path)
            if report:
                st.session_state["scan_result"] = report
                st.session_state["scan_done"]   = True
                st.success("Scan complete!")
                st.rerun()
            else:
                st.error("Scan ran but report not found.")
        else:
            st.error("Scan encountered an error. Check terminal output.")

# ── Results ───────────────────────────────────────────────────
if st.session_state.get("scan_done") and "scan_result" in st.session_state:
    report       = st.session_state["scan_result"]
    scan_results = report.get("results", [])
    all_matches  = report.get("all_matches_summary", report.get("all_matches", []))
    company      = report.get("company", "Unknown")

    # Compute summary metrics
    kev_count      = sum(1 for r in scan_results if r.get("actively_exploited"))
    critical_count = sum(1 for r in scan_results
                         if r.get("severity") == "CRITICAL" and "error" not in r)
    high_count     = sum(1 for r in scan_results
                         if r.get("severity") == "HIGH" and "error" not in r)
    patch_24h      = sum(1 for r in scan_results
                         if r.get("urgency") == "PATCH WITHIN 24 HOURS")

    st.markdown(f"### Scan Results — {company}")
    ts = report.get("scan_timestamp", "")[:19]
    st.caption(f"Scanned at {ts} | "
               f"{report.get('total_matches', len(all_matches))} CVEs matched across your stack | "
               f"{len(scan_results)} fully analysed")

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total CVE Matches", report.get("total_matches", len(all_matches)))
    with col2:
        st.metric("⚠️ Active Exploitation", kev_count,
                  delta="CISA KEV confirmed" if kev_count else None,
                  delta_color="inverse")
    with col3:
        st.metric("🔴 Critical / 🟠 High", f"{critical_count} / {high_count}")
    with col4:
        st.metric("🚨 Patch Within 24h", patch_24h)

    st.markdown("---")
    st.markdown("#### All Matched CVEs — Priority Ranked")
    st.caption("Full AI analysis on top results. Remaining matches shown below for visibility.")

    for r in scan_results:
        if "error" in r and "assessment" not in r:
            st.warning(f"{r.get('cve_id')} — analysis failed: {r.get('error','')[:80]}")
            continue

        a          = r.get("assessment", {})
        is_kev     = r.get("actively_exploited", False)
        score      = r.get("priority_score", 0)
        severity   = r.get("severity", "N/A")
        base_score = r.get("base_score", "N/A")
        urgency    = r.get("urgency", "")
        cve_id     = r.get("cve_id", "")

        # Asset string — handle both affected_assets list and flat fields
        assets_list = r.get("affected_assets", [])
        if assets_list:
            asset_str = ", ".join(
                f"{x.get('vendor','?')} {x.get('product','?')} ({x.get('exposure','?')})"
                for x in assets_list
            )
        else:
            vendor   = r.get("asset_vendor", "?")
            product  = r.get("asset_product", "?")
            exposure = r.get("asset_exposure", "?")
            asset_str = f"{vendor} {product} ({exposure})"

        with st.container():
            col_left, col_right = st.columns([5, 1])
            with col_left:
                kev_tag = " 🚨 **ACTIVE EXPLOITATION**" if is_kev else ""
                st.markdown(f"**{severity_emoji(severity)} {cve_id}**{kev_tag}")
                st.caption(f"Affects: **{asset_str}** | "
                           f"CVSS: **{severity} ({base_score})** | {urgency}")
            with col_right:
                color = score_color(score)
                st.markdown(
                    f"<div style='text-align:right;font-size:1.4rem;"
                    f"font-weight:bold;color:{color};'>{score}/100</div>",
                    unsafe_allow_html=True,
                )

            with st.expander(f"📋 View Full Report — {cve_id}"):
                tab1, tab2, tab3 = st.tabs(["Overview", "Attack Details", "Score & Citations"])

                with tab1:
                    what_it_is = a.get("what_it_is") or "Not available"
                    exploit    = a.get("exploitation_note") or "Not available"
                    st.markdown(f"**What it is:** {what_it_is}")
                    st.markdown(f"**Exploitation status:** {exploit}")
                    affected = a.get("affected_systems") or []
                    if affected:
                        st.markdown("**Affected systems:**")
                        for s in affected[:8]:
                            st.markdown(f"- `{s}`")
                    actions = a.get("immediate_actions") or []
                    if actions:
                        st.markdown("**Immediate actions:**")
                        for action in actions:
                            st.markdown(f"- {action}")
                    gaps = a.get("context_gaps")
                    if gaps:
                        st.info(f"ℹ️ Context gaps: {gaps}")

                with tab2:
                    scenario = a.get("realistic_attack_scenario") or []
                    if scenario:
                        st.markdown("**Realistic attack scenario:**")
                        for step in scenario:
                            st.markdown(f"- {step}")
                    techniques = a.get("attack_techniques") or []
                    if techniques:
                        st.markdown("**ATT&CK techniques:**")
                        for t in techniques:
                            st.markdown(
                                f"- **{t.get('id')}** {t.get('name')}: {t.get('relevance')}"
                            )
                    else:
                        st.caption("No ATT&CK techniques mapped for this CVE.")

                with tab3:
                    factors = r.get("priority_factors", [])
                    if factors:
                        st.markdown("**Priority score breakdown:**")
                        for factor in factors:
                            st.markdown(f"- {factor}")
                    c1, c2 = st.columns(2)
                    with c1:
                        st.metric("Priority Score", f"{score}/100")
                    with c2:
                        faith = r.get("faithfulness_score")
                        if faith:
                            st.metric("AI Faithfulness", f"{faith:.2f}")
                    citations = a.get("citations") or []
                    if citations:
                        st.markdown("**Citations (verified):**")
                        for c in citations:
                            st.markdown(
                                f"- *{c.get('claim','')}* → `{c.get('source','')}`"
                            )

            st.markdown("")

    # Remaining matches table
    analysed_ids = {r["cve_id"] for r in scan_results}
    remaining    = [m for m in all_matches if m.get("cve_id") not in analysed_ids]

    if remaining:
        st.markdown("#### Remaining Matches (not fully analysed)")
        table_data = [{
            "CVE ID":   m.get("cve_id", ""),
            "Score":    m.get("priority_score", 0),
            "Severity": m.get("severity", "N/A"),
            "Asset":    m.get("asset", f"{m.get('asset_vendor','')} {m.get('asset_product','')}"),
            "Exposure": m.get("asset_exposure", m.get("exposure", "N/A")),
            "KEV":      "YES" if m.get("actively_exploited") else "No",
            "Action":   m.get("urgency", ""),
        } for m in remaining]
        st.dataframe(table_data, use_container_width=True, hide_index=True)

else:
    st.info("👈 Click **Load Last Scan** to view existing results, or **Run Fresh Scan** to analyse your stack now.")
    st.markdown("""
**How it works:**
1. ThreatSight loads your asset inventory from the company profile
2. Matches each asset against 1,926 CVE chunks from NVD + CISA KEV
3. Computes a priority score (0–100) for each matched CVE
4. Runs the full 5-agent AI pipeline on the highest-priority matches
5. Delivers cited, AI-verified threat assessments for your specific stack
    """)
